### ISSUE TITLE
Add checkbox infront of each rows 

### ISSUE THREAD

**Issue by varpitoo** [ssuperczynski/ngx-easy-table#100]
Is there any way to add checkbox infront of each rows and bind an event on it ?

**Comment by ssuperczynski** [comment]
Hey, yes it is possible. I'll create demo for you on StackBlitz and add it here

**Comment by varpitoo** [comment]
There is one more question related to sorting.
Is it possible to give **orderEnabled=true** on the selected columns ?

Thanks

**Comment by ssuperczynski** [comment]
There you go:
- demo: https://ngx-easy-table.stackblitz.io/checkboxes
- code https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fcheckboxes%2Fcheckboxes.component.ts

Will push fix for `orderEnabled=true` in couple hours

**Comment by ssuperczynski** [comment]
Ok, I've decided to not extend that filter in the core.
There is much easier way to do that.
See this demo:
https://ngx-easy-table.stackblitz.io/custom-sort

and component:
https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fcustom-sort%2Fcustom-sort.component.ts

`ngOnInit` has method to sort column on init.

```
  ngOnInit() {
    this.sortByAge();
  }
```

**Comment by varpitoo** [comment]
Thanks for a great response. 
But i want something if we select something in header, then all the checkboxes select automatically.
We want the checkbox on header also.

Hoping for a positive response.

Thanks

**Comment by ssuperczynski** [comment]
I'll add it. Definitely it needs to be added to the table.

**Comment by ssuperczynski** [comment]
code: https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fcheckbox-default%2Fcheckbox-default.component.ts
demo: https://ngx-easy-table.stackblitz.io/checkboxes2

☀️ 🌴

**Comment by eran10** [comment]
how can this work with ng-template ?

**Comment by shpongly** [comment]
> how can this work with ng-template ?

Did you find any solution to this? I'm stuck with the same problem.

**Comment by varpitoo** [comment]
@shpongly 
Please find the code: <div class="card-body msgBody">
        <ngx-table [configuration]="configuration" [data]="data  | sortgridInAlphabetical: 'fullName'" [columns]="columns" [pagination]="paginationTable" (event)="eventEmitted($event)">
            <ng-template let-row>
                <td width="30%">
                    {{ row.fullName }}
                </td>
                <td width="15%">
                    {{row.phone}}
                </td>
                <td width="20%" >
                    {{row.email}}
                </td>
                <td width="15%" >
                    {{row.npi}}
                </td>
                <td width="13%" >
                    {{row.dea}}
                </td>
  
                <td width="7%">
                    <a class="icons edit">Edit</a>
                </td>
            </ng-template>
        </ngx-table>
    </div>

**Comment by varpitoo** [comment]
<ngx-table [configuration]="configuration" [data]="data  | sortgridInAlphabetical: 'fullName'" [columns]="columns" [pagination]="paginationTable" (event)="eventEmitted($event)">
            <ng-template let-row>
                <td width="30%">
                    {{ row.fullName }}
                </td>
                <td width="15%">
                    {{row.phone}}
                </td>
                <td width="20%" >
                    {{row.email}}
                </td>
                <td width="15%" >
                    {{row.npi}}
                </td>
                <td width="13%" >
                    {{row.dea}}
                </td>
                <td width="7%">
                    <a class="icons edit">Edit</a>
                </td>
            </ng-template>
        </ngx-table>

@shpongly Please find
