### ISSUE TITLE
Add optional filter per column

### ISSUE THREAD

**Issue by hadi-roudaki** [ssuperczynski/ngx-easy-table#101]
I was wondering if there is a way to add or remove column filter to selected columns. ?

**Comment by ssuperczynski** [comment]
Hey, yes it is possible. I'll create demo for you on StackBlitz and add it here

**Comment by ssuperczynski** [comment]
There you go.

Demo: https://ngx-easy-table.stackblitz.io/custom-filters
Code: https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fcustom-filters%2Fcustom-filters.component.html

Let me know if this is example you were thinking about

**Comment by hadi-roudaki** [comment]
thanks, mate,
thanks for everything, love how simple and neat ngx-easy-table is
