### ISSUE TITLE
Dragable rows 

### ISSUE THREAD

**Issue by hadi-roudaki** [ssuperczynski/ngx-easy-table#103]
Is there a way to have drag and drop implemented?

**Comment by hadi-roudaki** [comment]
I'm trying to migrate my website tables to use this plugin but few of them has sortablejs on them to simply add drag and drop rows to easily rearrange rows is this something to be done using this plugin

**Comment by ssuperczynski** [comment]
I'll add it, great idea

**Comment by ssuperczynski** [comment]
This feature is postponed to version 3.2 because of:
- https://github.com/swimlane/ngx-dnd/issues/81
- https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814
- https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833

**Comment by ssuperczynski** [comment]
Version 5.0 available.
Draggable rows added to the config `draggable: false | true` :)
