### ISSUE TITLE
Row index 

### ISSUE THREAD

**Issue by hadi-roudaki** [ssuperczynski/ngx-easy-table#104]
Can the rows have an index... I guess with angular I previously had  *ngfor= ”let i =index” but with using <ng-template> can mange to do the same anymore any suggestion on this issue

**Comment by ssuperczynski** [comment]
This example shows row index on click: 
- demo: https://ngx-easy-table.stackblitz.io/click-event
- code: https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fclick-event%2Fclick-event.component.html
