### ISSUE TITLE
File Export in CSV, Excel and text formats

### ISSUE THREAD

**Issue by varpitoo** [ssuperczynski/ngx-easy-table#105]
Thanks for the amazing library.

One more thing I need as to export in other formats in excel and text format.
Please add if possible!!

Thanks again.

**Comment by ssuperczynski** [comment]
There you go:
- demo https://ngx-easy-table.stackblitz.io/exports
- code https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fexports%2Fexports.component.ts

🌻 🌴
