### ISSUE TITLE
Want server side sorting on header column.

### ISSUE THREAD

**Issue by parmodmalik** [ssuperczynski/ngx-easy-table#106]
We want server side sorting in the same way on click of column heading.

Same way it is coming when we do orderenabled = true in config services

**Comment by ssuperczynski** [comment]
Could you check https://ngx-easy-table.stackblitz.io/server-sort
It shows correct server sorting by clicking table's headers.

**Comment by parmodmalik** [comment]
It's not working if in a column we have mix case i.e. some text are in upper case and some are in lower case.

**Comment by parmodmalik** [comment]
Can you please help me out here.

**Comment by parmodmalik** [comment]
**If we have data like below from server**
[{"phone":"+1 (878) 515-3653","age":32,"company":"AA","name":"AA","isActive":false},{"phone":"+1 (878) 515-3653","age":32,"company":"bb","name":"CC","isActive":false},{"phone":"+1 (878) 515-3653","age":32,"company":"cc","name":"CC","isActive":false},{"phone":"+1 (878) 515-3653","age":32,"company":"DD","name":"DD","isActive":false},{"phone":"+1 (878) 515-3653","age":32,"company":"ee","name":"EE","isActive":false}]

**and then we do sorting it's not working correctly.** 

Please find screenshot below.
![image](https://user-images.githubusercontent.com/12499883/39406387-a540c01e-4bd3-11e8-9d40-ee66b7c79769.png)

**Comment by ssuperczynski** [comment]
Ahh, now I know what is going on. Will fix it :)

**Comment by parmodmalik** [comment]
Any good news on that.

**Comment by ssuperczynski** [comment]
Sorry for delay, it should be ready until Monday

**Comment by parmodmalik** [comment]
@ssuperczynski Thanks for the update, its working fine.
