### ISSUE TITLE
Couldn't import excel2json 

### ISSUE THREAD

**Issue by varpitoo** [ssuperczynski/ngx-easy-table#109]
Hi,
Couldn't import below package.
**import { excel2json } from 'js2excel';**
Please help me out asap.

Thanks

**Comment by ssuperczynski** [comment]
`js2excel` is not included in the ngx-easy-table itself.
In the demo https://github.com/ssuperczynski/ngx-easy-table/issues/105 I've just shown how to use it with tables. You can use other library with excel support.
These custom solutions, give you much more flexibility.
