### ISSUE TITLE
Accessing complex objects in tables

### ISSUE THREAD

**Issue by Abe-Froman** [ssuperczynski/ngx-easy-table#117]
How can I expose properties on complex objects in my columns? For example, say my columns looks like this:

```
  columns = [
    { key: 'id', title: 'ID' },
    { key: 'createdDate', title: 'Submitted Date' },
    { key: 'status', title: 'Status' },
    { key: 'assignedTo', title: 'Assigned To' }
  ];
```

Because my `assignedTo` property is of type Person, in the table I get `[object object]` so what I really want to use as the key is `assignedTo.displayName` but that returns an empty string.

Additionally, in the row-template example what I would really love to do is display child object information when the chevron/arrow is clicked. Something like:

```
<ng-template #detailsTemplate let-row>
  <div>
    <h2 class="color-green">{{row.child.title}}</h2>
    {{row.child.status}}
  </div>
</ng-template>
```

Is this possible?

**Comment by ssuperczynski** [comment]
Hey @Abe-Froman thank for this issue. I've fixed it. Will do tests and soon it will be pushed as 3.1 tag

**Comment by ssuperczynski** [comment]
version 3.1 available :)

**Comment by ssuperczynski** [comment]
Just noticed, probably I fixed just first part of that issue. Let me know if below works. If not I'll fix it
```
<ng-template #detailsTemplate let-row>
  <div>
    <h2 class="color-green">{{row.child.title}}</h2>
    {{row.child.status}}
  </div>
</ng-template>
```
