### ISSUE TITLE
non-aligned checkbox

### ISSUE THREAD

**Issue by jmdmao** [ssuperczynski/ngx-easy-table#124]
The supplied css is declared in angular.json, but still the table loads this way. Do other css adjustments need to be made?

<img width="1440" alt="captura de tela 2018-06-06 as 10 48 13" src="https://user-images.githubusercontent.com/29717874/41046005-8d8b1e3a-6977-11e8-9d14-edc9e2c1f24e.png">

**Comment by jmdmao** [comment]
Taking advantage of the question space, is it possible to use checkbox of the first collumn in the `ng-template let-row`?

**Comment by ssuperczynski** [comment]
@jmdmao v4.0.1 is available on the npm :)
