### ISSUE TITLE
Logging in BaseComponent

### ISSUE THREAD

**Issue by Kavenon** [ssuperczynski/ngx-easy-table#126]
BaseComponent keeps logging all events. Is it necessary? Could you remove it or at least provide an option to configure logging?

https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/ngx-easy-table/components/base/base.component.ts#L199

**Comment by ssuperczynski** [comment]
Definitely, it needs to be moved under some config option.
I'll release version 4.1 today evening

**Comment by ssuperczynski** [comment]
v4.0.1 is available on the npm.
I've removed console.log. Option to enable logging will be added in v.5.0.0, so I'll keep this issue open

**Comment by ssuperczynski** [comment]
Version 5.0 available. 
Logger added to the config as `logger: false | true`
