### ISSUE TITLE
click events with detailsTemplate

### ISSUE THREAD

**Issue by zijam** [ssuperczynski/ngx-easy-table#130]
Is it possible to have an event emitted on expanding a row with detailsTemplate?

How do I change the arrow in a [detailsTemplate](https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Frow-template%2Frow-template.component.html) ?

**Comment by ssuperczynski** [comment]
I'll add this event in version 5.0. ETA 1 week.
I'll get back here with answer to the second question

**Comment by zijam** [comment]
Thx :)

**Comment by ssuperczynski** [comment]
Version 5.0 available.
I've added detailsTemplate event.
If you' like to change arrows - go to style.scss (or style.css), copy this file and put in you project somewhere (see https://github.com/ssuperczynski/ngx-easy-table/releases/tag/5.0.0 for more info) and customize lines 251 to 286.
