### ISSUE TITLE
The new version for angular 6 can used for angular 4?

### ISSUE THREAD

**Issue by zhaohongda1987** [ssuperczynski/ngx-easy-table#132]
Hi,
My project used angular 4.4.7, but the latest ngx-easy-table version is depended on angular 6, I can not build it. The error is metadata expect 4 but it is 3.
I also try to use old version of 1.2.0, it is depend on angular 4,but html file has error(Can't bind to 'data' since it isn't a known property of 'ngx-table'.). I also change ngx-table to ng2-table in html like readMe said, but it is also error. Anyone who knows how to solve it? Thanks very much

**Comment by ssuperczynski** [comment]
- version 2.4.4 supports Angular5
- version 4.0.0 supports Angular6

Unfortunately, table doesn't support Angular4 anymore.
