### ISSUE TITLE
set ngx-icon-arrow-up or ngx-icon-arrow-down at page reload

### ISSUE THREAD

**Issue by Digoro** [ssuperczynski/ngx-easy-table#138]
hi, first thank you for ngx-easy-table!

**currently programmed**
 - table config is `orderEnabled:true`
 - it is sorting on server side.
 - it store sort key and order value.

**question**

Can I set that icon when page reloads?
For example, if table sorted by `name` key, i want to show below icon at reload page
![screenshot from 2018-07-03 17 13 59](https://user-images.githubusercontent.com/6007757/42207338-ac14e08e-7ee4-11e8-9d32-c1149a3195cc.png)

**Comment by ssuperczynski** [comment]
Hey, I plan to add persisting the state in the next release.

Until then check this code: https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fcustom-sort%2Fcustom-sort.component.ts

This is not server side sorting, but similar idea. You put given action to `ngOnInit`
I'll try to add same demo for server side sorting at the end of today :)

**Comment by Digoro** [comment]
oh i see, thank you!

**Comment by ssuperczynski** [comment]
Option to persist column sorting has just been implemented.
See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.1
