### ISSUE TITLE
How can we move to the given page number?

### ISSUE THREAD

**Issue by alok-srivastav** [ssuperczynski/ngx-easy-table#144]
Suppose we are on the page 2 and we click one row and go on inner detail page.
But when we click browser back it take us to page 1. 

So do we have any option we can pass the page number and it will move to that page by default.

**Comment by alok-srivastav** [comment]
Hey Thanks.
Will it have support with Angular5?

**Comment by ssuperczynski** [comment]
This is good question, because Angular team ensures v6 has back compatibility with v5.
But it required many changes to upgrade to v6. I'll leave this issue open, and will check how, and if that works.

**Comment by parmodmalik** [comment]
any update on this?

**Comment by ssuperczynski** [comment]
Just stared work on 6.0 version, will be available in couple days :)

**Comment by ssuperczynski** [comment]
Release 6.0 available https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.0 :)

**Comment by alok-srivastav** [comment]
My project is in Angular5. Can we not have this **(persist state)** property in Angular4/5 project? 
In the documentation, it says to update to Angular 6.1

Do we need to update the project to Angular6?
