### ISSUE TITLE
load data dynamiclly

### ISSUE THREAD

**Issue by zbeedatm** [ssuperczynski/ngx-easy-table#146]
In ngOnInit (or can be moved to constructor) I have a call to service that getting back resources with this structure:

> [
            {Name: 'French', Uri: 'file:///C:.../french.csv'},
            {Name: "DB2", Dbms: "DB2", Host: "...", Port: 50000, DbName: "..."}
            ];

and I want to populate my table with it. The problem is that at this point resources are still not populated (Observable).
Can I set the data for table dynamically in code :  

```ts
resources: Observable<Array<any>>;
this.resources = this.resourcesService.getUser().pipe(
                        mergeMap( user => this.resourcesService.getResources(user.text()) ) 
  )
```

I can add .subscribe after the pipe for example and set the data.
Tried this but didn't work for me:

```ts
@ViewChild('resourcesTable') private resourcesTable;
this.resourcesService.getResources("admin")
                .subscribe( res => {this.data.push(res); this.resourcesTable.data = this.data;} );
```

How it can be done?

**Comment by zbeedatm** [comment]
maybe a two-way data binding is required (with event emitter) in this case... can I do some workaround ?

**Comment by ssuperczynski** [comment]
Hey, I'll add example to demos with `async`, thanks for investigation. :)

**Comment by ssuperczynski** [comment]
Demo with async example moved to https://ngx-easy-table.eu/#/async
