### ISSUE TITLE
Is it possible to change the filter placeholder?

### ISSUE THREAD

**Issue by zbeedatm** [ssuperczynski/ngx-easy-table#147]
Currently the placeholder (caption) of filter field is the same as the column title.
Is it possible to customize it? Without the need for custom-filters.
something like:

columns = [
    { key: 'phone', title: 'Phone', **placeHolder: 'Filter by Phone'** },
    { key: 'age', title: 'Age' },
    { key: 'company', title: 'Company' },
    { key: 'name', title: 'Name' },
    { key: 'isActive', title: 'STATUS' },
  ];

I have other issue related to css... the filter & search input controls are much smaller than other controls on the screen (smaller than the pagination controls for example). 
I'm using style: 'normal', tried big as well and it didn't help.

More than that, if I use the< ng-template let-row> to have my own template for rows, rows loose the table style at all and looks different. any idea why it's happening?

**Comment by ssuperczynski** [comment]
Hey,
answer for placeholder, please see https://github.com/ssuperczynski/ngx-easy-table/releases/tag/3.2.0

**Comment by zbeedatm** [comment]
Thanks.

1. Exactly what I needed.

2. I prefer the first option, but couldn't find in you example a css class name for the search & filter text boxes (like: :host /deep/ .ngx-table-**search**)
Why they aren't affected with style: 'big' at first place?

3. I'll try.
Meanwhile I'm using the basic way without templates so it's not blocking me. But I wanted to do something nice that when selecting a row (onCllick) to mark the corresponding checkbox of that row as selected (it's more convenience for the user)
