### ISSUE TITLE
[detailsTemplate]  title value

### ISSUE THREAD

**Issue by FahadAlanazi** [ssuperczynski/ngx-easy-table#148]
Hi,

is it possible to add a title for [detailsTemplate] column? currently it is empty,

I think it would be nice to change the value and position, (e.g. add it to the columns option in the ts file)

Thanks.

**Comment by ssuperczynski** [comment]
Hey, could you elaborate a bit. Could you add some examples or some mockup to help me understand this feature :)

**Comment by FahadAlanazi** [comment]
I mean, when i activate row details, a new column will be added to the most right with an arrow, that column do not have a title, I need a title for this column so the user can understand what this arrow for.

If needed, i can provide you a screenshot later to explain.

**Comment by ssuperczynski** [comment]
Ah, now I know. I'll add it in the next release

**Comment by ssuperczynski** [comment]
Version 6.0 has been released. I've added option to define custom button to show row details.

Please check https://stackblitz.com/github/ssuperczynski/ngx-easy-table?file=src%2Fapp%2Fdemo%2Ftemplate%2Ftemplate.component.html for example :)
