### ISSUE TITLE
Collapse/Expand Single row Item on Click

### ISSUE THREAD

**Issue by Dannyscholz** [ssuperczynski/ngx-easy-table#149]
Is it possible to collapse a singular row item on the click of a button? The configuration has a 'collapseAllRows' field that can be set to true.

I am trying to collapse a single row on click, WITHOUT using the default template expand button. I'm trying to use a custom button

**Comment by ssuperczynski** [comment]
This is cool feature, I'll add it in 6.0

**Comment by ssuperczynski** [comment]
Version 6.0 available. https://stackblitz.com/github/ssuperczynski/ngx-easy-table?file=src%2Fapp%2Fdemo%2Ftemplate%2Ftemplate.component.html for documentation :)
