### ISSUE TITLE
How to Reset Filters?

### ISSUE THREAD

**Issue by zbeedatm** [ssuperczynski/ngx-easy-table#150]
I want to add a Reset functionality that clear all the text that were typed in filter place holders and reset the search at once...
How can I get access to these placeholders and control them?

One more thing, if I filter by more than one column and then clear one filter only the data is reset like there are no other filters still populated! This is a wrong behavior.

**Comment by zbeedatm** [comment]
Hi @ssuperczynski ,
Is there a plane implement this PR? Is there ETA for it?
If not, I'll need to implement something by myself or to find a workaround meanwhile.

Regards.

**Comment by ssuperczynski** [comment]
I plan fix this issue in version 6.2 which will be available in around 2 weeks. Sorry for the delay

**Comment by zbeedatm** [comment]
Awesome! Thanks a lot.

2 issues will be included? The reset  & accumulative filters functionality (filter by more than one column)?

**Comment by ssuperczynski** [comment]
Version 6.2 available. https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.2
Reseting functionality will be available in version 6.3

**Comment by zbeedatm** [comment]
Hi,
Still have issue with multi filter, the first 2-3 input filters works fine but then the 3rd-4th one reset others and show more results than expected!

Regarding the Reset functionality that was supposed to be in version 6.3, I couldn't find that change when looking at the commits of that release:
https://github.com/ssuperczynski/ngx-easy-table/compare/6.3.0...master

**Comment by zbeedatm** [comment]
Awesome..
Regarding multi filter, do you think it's a bug or might be something
related to my implementation?
I used current version (8.0.1) and I still have this symptom when using
more than 2-3 filters!

Regards.

**Comment by ssuperczynski** [comment]
Feature has been released. See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/9.0 for more details.
