### ISSUE TITLE
Allow sort per column

### ISSUE THREAD

**Issue by matanarbel** [ssuperczynski/ngx-easy-table#152]
The sort definition (using orderEnabled) is done on the entire table.
Is it possible to define only specific columns as sortable? (maybe by adding "orderEnabled" in the columns object).

For example - I have a table with users list, and one of the columns is their image.
I want the users to be able to sort by some of the columns (like name), but I don't want them to sort by the image column.

**Comment by matanarbel** [comment]
Great, thanks!
It's a great table!

**Comment by ssuperczynski** [comment]
Release 6.0 available https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.0 :)
