### ISSUE TITLE
Add custom filters inside the table (like the built-in search)

### ISSUE THREAD

**Issue by matanarbel** [ssuperczynski/ngx-easy-table#153]
To maintain a clear UI, table filters should be inside the table (under the titles) - just like the default filters (using searchEnabled).
The documentation states that "For maximum flexibility tables doesn't have any built-in custom filters" - which makes sense, but it'd be great to have an option to define custom filters via ng-template, and having them placed as the first row of the table (under the headers).

Just like the [custom-filters example](https://ngx-easy-table.stackblitz.io/custom-filters), the code and logic will be written separately from the table, but the filters elements will be written the same way as the [basic template](https://ngx-easy-table.stackblitz.io/template).

Note that this row should **not** be sorted.

**Comment by ssuperczynski** [comment]
Release 6.0 available https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.0 :)
