### ISSUE TITLE
header column check box in ng template

### ISSUE THREAD

**Issue by eran10** [ssuperczynski/ngx-easy-table#154]
is there an option to create ng template for main checkbox column ? 
in your [example ](https://ngx-easy-table.stackblitz.io/checkboxes2)you have your own main checkbox but there is no option to change it,
i want option to create column of check with my own ng-template, is that possible ?

**Comment by ssuperczynski** [comment]
Sorry for delay, I have omitted this issue

New demo available on: https://ngx-easy-table.eu/#/checkboxes

**ts file**: https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/checkboxes/checkboxes.component.ts
**html** file: https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/checkboxes/checkboxes.component.html
