### ISSUE TITLE
Problem with numeric sorting on zero values

### ISSUE THREAD

**Issue by matanarbel** [ssuperczynski/ngx-easy-table#156]
When having a numeric column that contains zeros, the sorting messes it up (the zeros are sorted to the end, instead of the beginning).
It happens because the function FiltersService.getPath converts 0 to null:
`(xs && xs[x]) ? xs[x] : null`

And so the array `[1, 0, 3, 2]` gets converted to `[1, null, 3, 2]`, and then sorted to `[1, 2, 3, null]` (instead of `[0, 1, 2, 3]`).

Code reference:
src/app/ngx-easy-table/services/filters.service.ts:7

Fix suggestion:
`const result = p.reduce((xs, x) => (xs && typeof xs[x] !== 'undefined') ? xs[x] : null, o);`

**Comment by ssuperczynski** [comment]
Release 6.0 available https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.0 :)
