### ISSUE TITLE
Custom sort event (when clicking on the headers)

### ISSUE THREAD

**Issue by matanarbel** [ssuperczynski/ngx-easy-table#158]
I'd like to have a custom sort mechanism, which will fire when clicking on the headers (utilizing the built-in sort arrows and orderEnabled config).

I saw in issue #92 that this ability was removed due to errors and lack of flexibility, and that you suggest to sort the data that is provided to the table.
I also saw that it's possible to get events from the table when sort happens (in the [server sort example](https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fserver-sort%2Fserver-sort.component.ts)).

When I'm catching the "onOrder" event (when a user clicks a header), and then sorting the data according to my logic - the table also sorts it by the clicked column (and canceling my custom sort).
I'd like to be able to tell the table to emit the "onOrder" event, but **not** to perform the sort (and thus allowing custom sort).

For example, in the config object (or column config) pass a new flag: `orderEventOnly: true`.
Then, in the ["orderBy" function](https://github.com/ssuperczynski/ngx-easy-table/blob/6.0/src/app/ngx-easy-table/components/base/base.component.ts#L117), don't change the "sortBy" object if orderEventOnly is true.

@ssuperczynski - if you accept this concept, I'd be happy to add it.

**Comment by ssuperczynski** [comment]
Release 6.0 available https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.0 :)
