### ISSUE TITLE
Feature Request - Table Footer and GroupBy collapsed row sums.

### ISSUE THREAD

**Issue by alantarica** [ssuperczynski/ngx-easy-table#161]
Is it possible to get a summary or table footer for summary data? This would especially come in handy when using the "groupBy" table. For example, instead of just showing the count for whatever the table is being grouped by, it would allow you to show the sum of the columns given when the row is collapsed, and the item details when the row is opened.

A table footer would also be great to have to show the totals of each column, or whatever data we feed it.

**Comment by ssuperczynski** [comment]
Hey, I plan to add this feature. `groupBy` was just a beginning of bigger idea there. I'll definitely extend this functionality soon.

**Comment by alantarica** [comment]
Thanks.  We got around it in the mean time using row details with a custom grouping display.

**Comment by ssuperczynski** [comment]
Version 6.2 available with partially resolved items from this ticket. I've added option to define grouped row header.

Was:


Is:
<img width="976" alt="screen shot 2018-10-12 at 15 48 36" src="https://user-images.githubusercontent.com/6843074/46873373-a36a2b00-ce36-11e8-811e-63e504aa9f87.png">


I'll add more functionality in version 6.3, so I'll keep this ticket open.
See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.2

**Comment by shruti12345** [comment]
Pagination and global search is not working after implementing 'groupby' feature
