### ISSUE TITLE
Dragula breaks compatibility with SSR

### ISSUE THREAD

**Issue by attilaorosz** [ssuperczynski/ngx-easy-table#164]
First of all, thanks for this project!

Sadly, swimlane's dragula package breaks compatibility with SSR with error:
`ReferenceError: document is not defined`

I've found a similar error in dragula's repo but it complains about `global is not defined` there.

**Comment by ssuperczynski** [comment]
Yes, this is a known problem, I'm rewriting dragula to `cdkDrag`

**Comment by ssuperczynski** [comment]
Hey, latest release https://github.com/ssuperczynski/ngx-easy-table/releases/tag/7.0.0 has rewritten dnd, and removed dragula. Please check now :)
