### ISSUE TITLE
example isnt working

### ISSUE THREAD

**Issue by eran10** [ssuperczynski/ngx-easy-table#165]
your links here
https://stackblitz.com/github/ssuperczynski/ngx-easy-table?embed=1&file=app/components/basic/basic.component.ts

isn't working at all,
can you please fix it ?

**Comment by ssuperczynski** [comment]
Yes, something wrong with StackBlitz, I'm setting up new server, it should be ready by the end of this week

**Comment by ssuperczynski** [comment]
Demo moved to https://ngx-easy-table.eu/#/

**Comment by mhosman** [comment]
Still not working, ERR_CONNECTION_TIMED_OUT

**Comment by ssuperczynski** [comment]
@mhosman I've checked both https://ngx-easy-table.eu/#/ and https://stackblitz.com/github/ssuperczynski/ngx-easy-table and they work fine. Which address gives you ERR_CONNECTION_TIMED_OUT?

**Comment by mhosman** [comment]
Now it's working.
