### ISSUE TITLE
Sorted column by default

### ISSUE THREAD

**Issue by zbeedatm** [ssuperczynski/ngx-easy-table#169]
Hi,
I want to declare one of the columns to be sorted automatically while loading the table. like:

 columns = [
               { key: 'Name', title: 'Resource Name', placeholder: 'Filter', **sort: 'Asc'**},

Other alternative that I found (#92) didn't working for me cause I'm using an Observable array that doesn't have the sort method:
resources: Observable<Array<any>>;

What is the best way?

Regards.

**Comment by ssuperczynski** [comment]
I'll add it. I'll try to put it in the version 6.2 which will be released soon, or at least 6.3 :)

**Comment by zbeedatm** [comment]
Great, thanks a lot.

**Comment by ssuperczynski** [comment]
Version 6.2 available. See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.2
