### ISSUE TITLE
Can I get the 'checked' value in event "onCheckboxSelect"?

### ISSUE THREAD

**Issue by reevelau** [ssuperczynski/ngx-easy-table#179]
I enabled the checkboxes option in Config. Register an event listener. The listener is called every time I toggle the checkbox. 

However, I can't distinguish the checkbox value (checked=true/false) from the event parameter which is something like this

```
{
    event: "onCheckboxSelect",
    value: {
       event: 'on',
       row: {...},
       rowId: ..
    }
}
```

**Comment by ssuperczynski** [comment]
New version has been released https://github.com/ssuperczynski/ngx-easy-table/releases/tag/6.3.0 😃
