### ISSUE TITLE
Images in rows

### ISSUE THREAD

**Issue by mhurtado-swissbytes** [ssuperczynski/ngx-easy-table#185]
Hi!
Firstable,  i wanted to thank you for this awesome peice of work.

I'm facing some issues, I want to add images and custom buttons to the table, but I can't find a way to do it.

I think is not supported, but is there any way to do it?

Thanks in advance.

Cheers!

**Comment by ssuperczynski** [comment]
Hey, please check if column template works for you: https://ngx-easy-table.eu/#/col-template
https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/col-template/col-template.component.html

**Comment by ssuperczynski** [comment]
Could you fork https://stackblitz.com/github/ssuperczynski/ngx-easy-table and add your example.
With minimal reproduction I could help you

**Comment by mhurtado-swissbytes** [comment]
Thank you so much.

I wasn't a problem with your component, I'm new on angular, and it seems it failed to compiled cuz of the OnPush detection on my module.

My example now works perfect.

Again sorry to bother, and thank you so much for the support.

I really apreciate your time.
