### ISSUE TITLE
onCheckboxSelect does not have 'checked' value in event. 

### ISSUE THREAD

**Issue by mhurtado-swissbytes** [ssuperczynski/ngx-easy-table#190]
Hi dear friend.

Thank you so much for this awesome work.

I search over the issues and find oout that 23 days ago someone ask the same question, however i'm currently facing the same problem, because i can not distinguish the checkbox value from the event:

`{
  "event": "onCheckboxSelect",
  "value": {
    "event": {
      "isTrusted": true
    },
    "row": {
            ...
    },
    "rowId": 0
  }
}`

I also check the sample [here](https://github.com/ssuperczynski/ngx-easy-table/tree/master/src/app/demo/checkboxes)

but it does not show how to remove from the Set or how to know if the value was checked.

I don't know if i missing something and i really thank you in advance for your help.

Greetings!

**Comment by ssuperczynski** [comment]
Hey @mhurtado-swissbytes,
when you open this demo: https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/checkbox-default/checkbox-default.component.ts

method `eventEmitted` has `$event` object.
Just try to use this `console.log($event.value.event.target.checked);`

**Comment by mhurtado-swissbytes** [comment]
Thank you so much @ssuperczynski  that fits perfect my needs!

keep the good work!

Also thank you @alok-srivastav  for the support.
