### ISSUE TITLE
Feature Request- Table doesn't support pagination for 'groupby' feature

### ISSUE THREAD

**Issue by shruti12345** [ssuperczynski/ngx-easy-table#193]
Currently 'Groupby' feature does not support pagination. Even if we try to add addition pagination template it is not supporting. can you please add pagination to 'groupby' feature in next release?

**Comment by ssuperczynski** [comment]
Hey, indeed pagination was not implemented for grouped rows. Added it, and will be included in the version 8.
Release probably tomorrow

**Comment by shruti12345** [comment]
Thank you so much @ssuperczynski

**Comment by shruti12345** [comment]
Hi @ssuperczynski , when you will release 8th version?

**Comment by ssuperczynski** [comment]
Hi @shruti12345, version 8.0.1 is public available. I've added normal pagination.
Server pagination, sorting and filtering should be added with next release - it is on my TODO list.
Thanks for using table!
