### ISSUE TITLE
Allow custom classes

### ISSUE THREAD

**Issue by dburner** [ssuperczynski/ngx-easy-table#197]
**Is your feature request related to a problem? Please describe.**
Allow custom class for table element (to allow custom boostrap themeing).

**Describe the solution you'd like**
Maybe add another property in config that maps different classes for example:
```
var config = {
   styles: {
      tableElement: "table table-bordered table-striped table-sm" // allow multiple classes
   }
}
```

**Describe alternatives you've considered**
I'm not verry familiar with Angular 2+ but there may be another option to make something like an `INgxTableSettings` service that will override the classes maybe.
Would it be possible to use the `<ng-template>` tag for the `<table>` element as well?

**Additional context**
Same thing goes for the pager I guess (allow placing of boostrap classes).
I would like my application to be compatible with styles from this website: https://bootswatch.com/, therefore if I use boostrap classes in ngx easy table I can apply any skin from that site.

Also thanks for the awesome library :+1:

**Comment by ssuperczynski** [comment]
I just started work on this feature, it was on my TODO list :). Version 8 will be released today, so this feature should be available soon with version 9.

**Comment by dburner** [comment]
Oh, great to hear it, thanks !

**Comment by ssuperczynski** [comment]
I'll leave this issue open, it will help me to keep it in mind

**Comment by ssuperczynski** [comment]
Feature has been released. See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/9.0 for more details.
