### ISSUE TITLE
How to change styling of row?

### ISSUE THREAD

**Issue by ashanren** [ssuperczynski/ngx-easy-table#198]
Currently you have an example showing how to change the background-color single cell while using the ng-template. I was wondering if it was possible to change the entire row background-color. You can't put the styling in the ng-template so i wondering if there is a specific way to do this. Thanks

**Comment by ssuperczynski** [comment]
Hey, sorry for the late response, I thought I put response here. Feature already added, and it will be available in around 2 weeks with 9th release.

**Comment by ashanren** [comment]
Ah. That's good to know. Thanks

**Comment by ssuperczynski** [comment]
Feature has been released. See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/9.0 for more details.
