### ISSUE TITLE
Wiki installation bug

### ISSUE THREAD

**Issue by prom00** [ssuperczynski/ngx-easy-table#205]
**Is your feature request related to a problem? Please describe.**
config-service.ts has a small error. It states the property 'border: true'. It seems like this is borderless now.

**Describe the solution you'd like**
Change the name from 'border' to 'borderless'

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ssuperczynski** [comment]
Thank you @prom00! Fixed 🚀
