### ISSUE TITLE
Allow custom component for number of items on page

### ISSUE THREAD

**Issue by dburner** [ssuperczynski/ngx-easy-table#207]
I would like a custom component for number of items on page.

I would like to be able to provide a template or custom component for the number of items on the page and make something like this:
![image](https://user-images.githubusercontent.com/2664398/50989240-7bfb2b00-1517-11e9-97eb-53f0efbd5378.png), taken from ng-table.com.

The problem now is that the dropdown does not perform quite nice when it is at the bottom r8ght screen.

Thanks

**Comment by ssuperczynski** [comment]
I'll try to add this functionality in version 10.0, first I had to release version 9.0 to implement part of this feature, so with next release it should be added completely.

**Comment by ssuperczynski** [comment]
I'll add it to version 9.1 this week ⭐️

**Comment by ssuperczynski** [comment]
Feature has been implemented.

You can define your own template for this section:

1. In the configuration set `paginationRangeEnabled` to false
2. Build your own html with numbers you would like to.
3. Use https://ngx-easy-table.eu/#/api-doc `API.setPaginationDisplayLimit` when you click on the given number.
