### ISSUE TITLE
I want to display line Numbers in each row, how to get the line number

### ISSUE THREAD

**Issue by zyn926** [ssuperczynski/ngx-easy-table#208]
I want to display line Numbers in each row, how to get the line number.

**Comment by ssuperczynski** [comment]
Hey, please check `let-index="index"`.

```html

<td>
  {{index}}
</td>
```
Demo: https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/template/template.component.html

**Comment by zyn926** [comment]
> Hey, please check `let-index="index"`.
> 
> ```
> <td>
>   {{index}}
> </td>
> ```
> 
> Demo: https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/template/template.component.html

ok，thanks
