### ISSUE TITLE
Manually set the selectedRow for highlighting

### ISSUE THREAD

**Issue by Michael-Molloy** [ssuperczynski/ngx-easy-table#212]
Hello, 

I want to highlight a row in the nxg-table by settings manually the selectedRow. Can I?

Michael

**Comment by ssuperczynski** [comment]
Hey, yes I plan to release version 9.0 this week with this feature 🚀

**Comment by ssuperczynski** [comment]
Feature has been released. See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/9.0 for more details.
