### ISSUE TITLE
How to get / set current table state?

### ISSUE THREAD

**Issue by fedotxxl** [ssuperczynski/ngx-easy-table#213]
A table has a state:

1. Ordering
2. Pagination

I wanna sync this state with URL -> table should persist its state to URL and restore it on page load. How can I do it?

**Comment by ssuperczynski** [comment]
Hey, this feature will be available soon with 9.0 version.

**Comment by ssuperczynski** [comment]
Feature has been released. See https://github.com/ssuperczynski/ngx-easy-table/releases/tag/9.0 for more details.
