### ISSUE TITLE
Problem with "sort-header" row - now it always placed on the DOM

### ISSUE THREAD

**Issue by matanarbel** [ssuperczynski/ngx-easy-table#220]
The `sort-header` row (`tr`) used to be included with `*ngIf` only when `searchEnabled` flag is true and there isn't a filter template.
In [this commit](https://github.com/ssuperczynski/ngx-easy-table/commit/6ab04bd3f5a988c0f7b769e4de43ac2cb5eed3fb) you've changed it to be rendered always (no `*ngIf`) and you've added a relevant class for hiding or showing that row.

Other then the fact there's no reason to render it to the DOM if it'll never be used, it throws errors in case there are defined columns with no `key` attribute (it might not be best practice, but that's the way it's define in several places in our system).

I think you should return the `*ngIf`.
What do you say?

![image](https://user-images.githubusercontent.com/2864313/53882159-368e4200-401e-11e9-8808-04248e1bf38a.png)

**Comment by eran10** [comment]
+1

**Comment by ssuperczynski** [comment]
Fixed, will release today as v9.1.1

**Comment by matanarbel** [comment]
Thanks!!
Amazing super fast response!!! 💪
