### ISSUE TITLE
API interface requires event to fire

### ISSUE THREAD

**Issue by mm1c** [ssuperczynski/ngx-easy-table#226]
Hello Everyone,

I would like to use API to set row styles and it's working only when an event fires the style change.

```ts
click() {
    this.table.apiEvent({
      type: API.setRowStyle,
      value: { row: 1, attr: 'background', value: '#fd5e5ed4' },
    });
  }
```

Above code works if attached to a button, like `(click)=click()`, but it doesn't work if it's called without an event fired, like
 
```ts
    this.http.get(url).subscribe((resp: any) => {
      if(resp.success) {
          this.table.apiEvent({
            type: API.setRowStyle,
            value: { row: 1, attr: 'background', value: '#fd5e5ed4' },
          });
        }
    }
```

Is this the intended behaviour or is this a bug?

Hope, it's not a duplicate. In case it is, please redirect me to answer. (I couldn't find it.)

Thank you!

**Comment by ssuperczynski** [comment]
Hey @mm1c,

API works after view has been initialised, so to activate API call you need to add this action to  `ngAfterViewInit`. See https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/api/api.component.ts#L40 for working example.

**Comment by mm1c** [comment]
Hi, thanks for the quick answer.

I have a search form that sends a http request to an api and the result should be viewed in an ngx-easy-table. After user presses search button, the below code executes (shortened version) and when result arrives, I want to set row styles based on color parameters included from the result. But this doesn't work for me.

`  private getData(searchType, parameters) {
    this.tableConfig = ConfigService.config;    
    const params = this.setParamString(parameters);
    const url = this.url + params;

    this.http.get(url).subscribe((resp: any) => {
      if(resp.success) {
        this.shipmentsData = [];
        for(let sh of resp.shipments) {
          this.shipmentsData.push(sh);
        }
        this.pagination.count = (this.pagination.count === -1 || this.pagination.searchType != searchType) ? resp.pagination.total : this.pagination.count;
        this.pagination = { ...this.pagination };

        if(this.shipmentsData.length > 0) {
            // BELOW IS JUST SAMPLE CODE, CORRECT SOLUTION TO BE IMPLEMENTED
            // below code doesn't set row style, but it's after view init I think
          this.table.apiEvent({
            type: API.setRowStyle,
            value: { row: 1, attr: 'background', value: '#fd5e5ed4' },
          });
        }
      }
    });
  }`

Thanks!

**Comment by ssuperczynski** [comment]
Could you add `ChangeDetectorRef` to the constructor and run `this.cdr.detectChanges();` just before `apiEvent`. 

```ts
  constructor(private readonly cdr: ChangeDetectorRef) {}

private getData(searchType, parameters) {
...
  this.http.get(url).subscribe((resp: any) => {
    ...
    this.cdr.detectChanges();
    this.table.apiEvent({
      type: API.setRowStyle,
      value: { row: 1, attr: 'background', value: '#fd5e5ed4' },
    });
  }
...
}
```

**Comment by mm1c** [comment]
Now it's coloring the row, but doesn't load data into the table. Just the spinning icon appears.

The problem is this line above the apiEvent call: `this.cdr.detectChanges();`

When it's removed, data appears in table but no row style change.

**Comment by mm1c** [comment]
Please ignore my previous comment. I left in `this.tableConfig.isLoading = false;`, that's why rows didn't appear. Thank you!

**Comment by ssuperczynski** [comment]
Glad it works. Happy coding!
