### ISSUE TITLE
Pagination bug when having multiple tables on the same page

### ISSUE THREAD

**Issue by matanarbel** [ssuperczynski/ngx-easy-table#229]
When having more than 1 table on the same page, the pagination of all of the tables is the same (as the first table).

For example, if the pagination is set to 10 rows per page, and we have 2 tables - the first with 30 rows and the second with 100 rows, they both show 3 pages (instead of 10 pages in the second table) - and the pagination in the second table doesn't work at all.

**Comment by ssuperczynski** [comment]
Please navigate to the https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/many-tables/many-tables.component.html. You need to add `[id]="'someTableId'"` to work with multiple tables at one page

**Comment by matanarbel** [comment]
Thanks!!!!

**Comment by samheihey** [comment]
I was having the same problem, the second table pagination works in the first place, and after the page is changed (from page 1 to page 2, then page 2 back to page 1), the number of pagination rows changed back to the value in the first table

**Comment by ssuperczynski** [comment]
Could you create Stackblitz minimal reproduction, I'll try to check if this is a bug.

**Comment by samheihey** [comment]
> Could you create Stackblitz minimal reproduction, I'll try to check if this is a bug.
@ssuperczynski 

I just followed the sample in:
https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/many-tables/

For the configuration, I just changed the Basic Configuration rows to 3, and the Advanced Configuration rows to 6

**Comment by ssuperczynski** [comment]
@samheihey Please check my updated StackBlitz: https://stackblitz.com/edit/angular-phl4c6?file=src/app/app.component.ts

I updated Configs recently, by using `DefaultConfig` it should work fine

**Comment by ssuperczynski** [comment]
Nope, still something wrong, I'll try to debug it.

**Comment by ssuperczynski** [comment]
@samheihey Fix available under 10.1.1
