### ISSUE TITLE
Set pagination to specific row

### ISSUE THREAD

**Issue by Simsal** [ssuperczynski/ngx-easy-table#232]
I have a table with appointments. There is a column with a date property and it has some dates in the past and in the future.

ATM I just show them sorted from oldest to newest.

I'd like to be able to set the page to the one that contains the next upcoming appointment.

I tried to play around with `API.setPaginationCurrentPage` but I weren't able to get it going. Maybe you can give me a hint, if it is possible?

**Comment by ssuperczynski** [comment]
Could you add minimal reproduction. I can help if you could create some StackBlitz example

**Comment by Simsal** [comment]
Hey, I created an example.
[](https://stackblitz.com/edit/angular-oodtnf)
If you sort the BeginningDate from oldest to newest than there are two pages where all tasks lay in the past. The next possible appointment is on 17.04.2019 on page 3. So I'd like to load the table initially on page 3.

**Comment by ssuperczynski** [comment]
I've forked your example, please check if this is what you are looking for: https://stackblitz.com/edit/angular-spitvw?file=src/app/app.component.ts

The main concept is to fire API event in `ngAfterViewInit`.

**Comment by Simsal** [comment]
Thank you very much. With this example I can change the page.

What I would need now, is a possibility to get the items on each page to determine to which page I should change...
Is there a built in way?
Otherwise I could sort the array beforehand and count manually which index has the next date

**Comment by Simsal** [comment]
Ty, got it to work the way I want.

Just a hint for the apiEvent calls:
If the table is wrapped within a *ngif than the selection of the table with viewchild doesn't work.
Not a problem of your library. Just wanted to mention it in case someone reads this issue.

**Comment by ssuperczynski** [comment]
Thanks, will add it to the documentation too. 🚀
