### ISSUE TITLE
Can we create a new column and modified value on that column later ?

### ISSUE THREAD

**Issue by 1312801** [ssuperczynski/ngx-easy-table#241]
Hi, I already have table with ngx-easy-table. Now I want to create new column by pressing on button. Although I tried to create column by adding to column's object, then displaying it successfully. 
I wanted to edit a row after that.

The problem is the table use Elementref and Templateref to edit value in a column, so that I have to edit html file to display it. 

Is there any way to edit value on the column without using ElementRef and TemplateRef ? I can't find any APIs for this neither.

**Comment by ssuperczynski** [comment]
Sorry TemplateRef, ElementRef are the only solution for now.
