### ISSUE TITLE
"Cannot read property 'nativeElement' of undefined" for PaginationComponent

### ISSUE THREAD

**Issue by samheihey** [ssuperczynski/ngx-easy-table#242]
Bug: Cannot read property 'nativeElement' of undefined
File: node_modules/ngx-easy-table/fesm5/ngx-easy-table.js.PaginationComponent.onClick (ngx-easy-table.js:173)
Attempt fix:
```
function (targetElement) {
        /** @type {?} */
        if(this.paginationRange['nativeElement'] != undefined){
            var clickedInside = this.paginationRange.nativeElement.contains(targetElement);
            if (!clickedInside) {
                this.showRange = false;
            }
        }
    };
```

**Comment by samheihey** [comment]
Attempt fix 2:

function (targetElement) {
        /** @type {?} */
        if(this.paginationRange != undefined && this.paginationRange['nativeElement'] != undefined){
            var clickedInside = this.paginationRange.nativeElement.contains(targetElement);
            if (!clickedInside) {
                this.showRange = false;
            }
        }
    };

**Comment by ssuperczynski** [comment]
Could you point me when you get this error `node_modules/ngx-easy-table/fesm5/ngx-easy-table.js.PaginationComponent.onClick (ngx-easy-table.js:173`

**Comment by samheihey** [comment]
I was having more than one easy tables, set them with different ID to make sure they don't interfere with each other and also set the pagination, it works fine, but the error pops up in the console.

**Comment by ssuperczynski** [comment]
This example has 2 tables at one page and there are no errors: https://ngx-easy-table.eu/#/many-tables

Could you check if you implemented it like here: https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/many-tables/many-tables.component.html

If error still appears, could you add minimal reproduction.

**Comment by danielsantil** [comment]
I am also getting this error.

Google Chrome's console throws error _"Cannot read property 'nativeElement' of undefined"_, and the same error is thrown with the message: _ERROR TypeError: "this.paginationRange is undefined"_ when using Mozilla Firefox.

Looking at my Config object, the property `paginationRangeEnabled` is set to `false`. Once I set it to `true`, the error disappears.
I could use this fix as a workaround, but it changes my layout, as I don't need a pagination range to be displayed.

This is my configuration object:
```
config = {
    searchEnabled: false,
    headerEnabled: true,
    orderEnabled: true,
    paginationEnabled: true,
    paginationRangeEnabled: false,
    exportEnabled: false,
    clickEvent: true,
    selectRow: true,
    selectCol: false,
    selectCell: false,
    rows: 5,
    additionalActions: false,
    serverPagination: false,
    isLoading: false,
    detailsTemplate: false,
    groupRows: false,
    collapseAllRows: false,
    checkboxes: false,
    resizeColumn: false,
    fixedColumnWidth: false,
    horizontalScroll: false,
    draggable: false,
    logger: false,
    showDetailsArrow: false,
    showContextMenu: false,
    persistState: false,
    tableLayout: {
        style: 'tiny',
        theme: 'light',
        borderless: false,
        hover: true,
        striped: false,
    },
};
```

NgxEasyTable version: 10.1.1
Angular CLI: 8.0.6
Angular: 8.1.0

**Comment by ssuperczynski** [comment]
Thank you for the bug reproduction. I'll fix it today.

**Comment by ssuperczynski** [comment]
Hey, @samheihey @danielsantil fix released as https://github.com/ssuperczynski/ngx-easy-table/releases/tag/10.1.2
