### ISSUE TITLE
virtual pages of table

### ISSUE THREAD

**Issue by techaks** [ssuperczynski/ngx-easy-table#246]
> i want to load total count of records in once and then call page one by one

**Comment by ssuperczynski** [comment]
I am sorry, I don't know what do you mean. Could you elaborate.

**Comment by ssuperczynski** [comment]
Closed due to inactivity.

**Comment by gurpreetbal** [comment]
it like batch loading, get data of first n rows  for page 1 and total no. of pages from server then next page data when click on respective page
