### ISSUE TITLE
Provide an example where state is synced with URL

### ISSUE THREAD

**Issue by fedotxxl** [ssuperczynski/ngx-easy-table#247]
Good practice to sync state with URL so a user can refresh the page and get the same state. LocalStorage solution is hack which do not allow user to copy URL and send it to another user. 

I tried to implement syncing table state with URL and it made me a lot of pain. Can you suggest your solution?

**Comment by ssuperczynski** [comment]
Please check example: https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/persist-state-router/persist-state-router.component.ts

and demo: https://ngx-easy-table.eu/#/persist-state-router/column%3Dphone&sort%3Ddesc

**Comment by fedotxxl** [comment]
The state should be synced between URL and table. Right now URL doesn't change when user changes column order
