### ISSUE TITLE
Highlight the searched text in the table while filtering

### ISSUE THREAD

**Issue by mamohanc** [ssuperczynski/ngx-easy-table#249]
Highlight the searched text in the table while filtering

From the Search Example on the website, 
for suppose i search for KO as company name, the rows are filtered (filtered functionality), can the text KO under company column be highlighted as well 

I was looking for examples and md-highlight-text="searchTerm"
 and another application of ng-bind-html were provided as solutions

**Comment by ssuperczynski** [comment]
I try to keep tables as easy as possible and I don't plan to add this functionality to the core. But you can achieve the same effect by using https://ngx-easy-table.eu/#/col-template and some text concatenation and some css classes

**Comment by mamohanc** [comment]
ok. 
Yup sounds reasonable
