### ISSUE TITLE
export as pdf with custom layout

### ISSUE THREAD

**Issue by anuj509** [ssuperczynski/ngx-easy-table#250]
---
name: Export PDF with custom options
about: Export table as pdf with minimal styling. It should also support page break if table contains rows specified in threshold(rows per page). First page might contains additional html or syling like meta details.

---

**Is your feature request related to a problem? Please describe.**
Requesting feature As it is useful. For the same reason I have to remove this package because I couldn't find any work arounds.

**Describe the solution you'd like**
table with options like per page rows. adding meta details and styling. Adding meta details on first page.

**Describe alternatives you've considered**
jspdf with html2canvas. But, this has problem as we need to render html and then I can access in as canvas and then pdf conversion. However jspdf is quite descriptive and docs has a lot of methods.

**Comment by ssuperczynski** [comment]
I am sorry, but I don't plan to add this feature, because is to complicated. I try to keep tables as easy as possible. However, you can add this feature by yourself, please check csv, or excel examples on https://ngx-easy-table.eu/#/exports
