### ISSUE TITLE
Number of Rows per Page ?

### ISSUE THREAD

**Issue by Was85** [ssuperczynski/ngx-easy-table#259]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to get the number of rows per page dynamically , 

**Describe the solution you'd like**
Give the user feedback in the table footer about how many rows (Items) we have in this page, its really helpfull to tell for example : "We have found 33 customers. Showing {{numberOfCustomerPerPage}} of 33 Customers"

**Describe alternatives you've considered**
I am aware we have "Get Pagination current", "Get total","Get last" in which we can use to get the the row per page.However , this is too much work here.

**Additional context**

![image](https://user-images.githubusercontent.com/32059289/63924937-796b2880-ca49-11e9-9ebb-b85203bbef04.png)

**Comment by ssuperczynski** [comment]
Hey @Was85 this feature has just landed in version https://github.com/ssuperczynski/ngx-easy-table/releases/tag/11.0.0

**Comment by Was85** [comment]
Hello @ssuperczynski  ,thank you for reply.
I am getting this  API.getNumberOfRowsPerPage does not exist on type  'type of Api' ? What I am missing here ?

**Comment by ssuperczynski** [comment]
Could you try to `rm -rf node_modules`. I just did below steps using clean project and it works:

```html
    <button (click)="getNumberOfRowsPerPage()">getNumberOfRowsPerPage</button>
    <span>itemsPerPage: {{itemsPerPage}}</span>
    <ngx-table
      #table
      [configuration]="configuration"
      [data]="signatures$ | async"
      (event)="onSelectSignatures($event)"
      [columns]="columns">
    </ngx-table>

```

```typescript
  itemsPerPage: number;
  @ViewChild('table') table: APIDefinition;
  getNumberOfRowsPerPage(): void {
    this.itemsPerPage = this.table.apiEvent({
      type: API.getNumberOfRowsPerPage,
    });
  }
```
