### ISSUE TITLE
radio buttons instead of check boxes

### ISSUE THREAD

**Issue by gurpreetbal** [ssuperczynski/ngx-easy-table#260]
Is ther any way to convert checkboxes to radio buttons or make them behave like radio buttons?
I only want to select one row at a time.

**Comment by ssuperczynski** [comment]
Yes, please check https://ngx-easy-table.eu/#/checkboxes

**Comment by gurpreetbal** [comment]
<ngx-table 
		[data]="data_array"   
		[summaryTemplate]="summaryTemplateRef" 
		[configuration]="configuration"   
		#table 
		[columns]="columns_array"  
		(event)="eventEmitted($event)" >
		<ng-template let-row let-index="index">
		<td>
			<div class="form-group">
				<label class="form-checkbox">
          <input type="radio" name="selected" (change)="onChange(row)">
          <i class="form-icon"></i>
        </label>
			</div>
		</td>
		</ng-template>
        </ngx-table>

Now only radio buttons are show in grid, no data.

![radio](https://user-images.githubusercontent.com/25562430/64690777-d1c11200-d4ae-11e9-84a9-49fac5c3eff9.JPG)

**Comment by ssuperczynski** [comment]
Please check carefully the correct template https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/checkboxes/checkboxes.component.html

**Comment by ssuperczynski** [comment]
@gurpreetbal I've updated demo, please check https://ngx-easy-table.eu/#/checkbox-as-radio
