### ISSUE TITLE
Checkbox template not working with row template

### ISSUE THREAD

**Issue by shpongly** [ssuperczynski/ngx-easy-table#261]
I follow your example on checkbox-default. I'm trying to add checkbox column to each row in the table and also to the header by setting 'true' in the checkbox config obj. I'm using a template for the rows. However, a checkbox is rendered only in the header column. Checkboxs in each row are not being rendered. if I delete the the template, the checkboxs are rendered.

I beleive its a bug.

Angular 8
ngx-easy-table 10.1.2

Thanks

**Comment by ssuperczynski** [comment]
Could you add a minimal reproduction
