### ISSUE TITLE
Server pagination

### ISSUE THREAD

**Issue by kayaz** [ssuperczynski/ngx-easy-table#265]
Let's say we have 10k records in database. We want to paginate them every 4 record. When we run your code with MySQL we must load all 10k record and just then we see pagination bar because script know how many items are.

So i think good option is add itemsCount parameter to data array. Like so:
```
{
    "itemsCount": 4,
    "items": [
		{
			"id": 0,
			"name": "Item 0",
			"price": "$0",
			"amount": 3
		},
		{
			"id": 1,
			"name": "Item 1",
			"price": "$1",
			"amount": 4
		},
		{
			"id": 2,
			"name": "Item 2",
			"price": "$2",
			"amount": 8
		},
		{
			"id": 3,
			"name": "Item 3",
			"price": "$3",
			"amount": 2
		}
	]
}
```

Then on first load we ask for first 4 items, and we know how many are there so we can calculate pagination bar.

**Comment by ssuperczynski** [comment]
This is implemented, see https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/server-pagination/server-pagination.component.ts#L75

**Comment by kayaz** [comment]
This dont work. Did you test this with MySQL? In respond from API you must get item count not in your script.

**Comment by ssuperczynski** [comment]
Angular doesn't speak directly with the database. Use custom field in the API response and set it https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/server-pagination/server-pagination.component.ts#L75 as `response.length`

**Comment by kayaz** [comment]
Ok, i got it now and i know that Angular doesn't speak directly with the database. How this works when you using server pagination and search row? This gonna search in what you downloaded from the database right? Not in whole database?
