### ISSUE TITLE
How to add an custom html element into the pagination area ?

### ISSUE THREAD

**Issue by audiofreak1** [ssuperczynski/ngx-easy-table#274]
I like to add custom html code in the pagination area.
I recognized the bootsprap https://ngx-easy-table.eu/#/custom-pagination example.

Ho can i just use another html syntax or in my case just add an custom button  in your existing pagination area / component ?

Thanks!

**Comment by ssuperczynski** [comment]
Custom pagination can be implemented as shown here https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/custom-pagination/custom-pagination.component.ts#L54
