### ISSUE TITLE
Changing configuration cause page number problems

### ISSUE THREAD

**Issue by lukaszblasz** [ssuperczynski/ngx-easy-table#276]
After changing configuration object to completely new one, 'page numbers' list stop working correctly.

**How to reproduce:**

To reproduce issue we can use example server side pagination from demos:
https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/server-pagination/server-pagination.component.ts

1. Add line:
`this.configuration = { ...this.configuration };`
for example in line 80, inside subscribe function. Above line is simply replacing old configuration with new one without any change, of course we can make some change there like isLoading or something else, but its not needed to see error.

2. Click on visible page numbers for example to change visible items from 10 to 25. 
3. 25 items are loaded but number still shows 10.
4. After clicking on next page, to show next 25 items, 10 items is shown. Instead of 25.

Conclusion: After changing configuration object to new one, 'visible items' functionality stop working correctly.

**Expected result**

New configuration object should not break the 'visible items' functionality.

**Comment by khalifa005** [comment]
same issue did you find out why
@lukaszblasz

**Comment by khalifa005** [comment]
@lukaszblasz 

figure it out use
```

ngAfterViewInit(): void {
    
    this.table.apiEvent({
      type: API.setPaginationDisplayLimit,
      value: 5,
    });

    // this.paginationTotalItems = this.table.apiEvent({
    //   type: API.getPaginationTotalItems,
    // });
    
    this.cdr.detectChanges();


  }
```
