### ISSUE TITLE
Could be posible to make column variable accesible from cellTemplate TemplateRef?

### ISSUE THREAD

**Issue by piscisferro** [ssuperczynski/ngx-easy-table#278]
Hi!

Just as the title said. Right now I have access to the row object when inserting a TemplateRef using cellTemplate, but I cannot access to the column object for that cell. 

This is because I'm building a lot of components around this table using a custom Column object extended from the one this table uses to provide more information for the other components. Being able to use this infomation for the table cellTemplates would be wonderful and will make me able to remove a lot (and really a lot) of workaround code I have currently around for each component. 

In case the table already provides this access.. How can I access this object? I didn't manage to access it. 

thanks in advance!

**Comment by ssuperczynski** [comment]
Version 12.00 with this feature is now available https://github.com/ssuperczynski/ngx-easy-table/releases/tag/12.0.0

:)
