### ISSUE TITLE
Demo is broken on IE11

### ISSUE THREAD

**Issue by vinayakpatil** [ssuperczynski/ngx-easy-table#280]
![image](https://user-images.githubusercontent.com/3096223/71399585-221d4380-264a-11ea-9de8-bcea36f5a444.png)

**Comment by ssuperczynski** [comment]
Hey, thanks for report.
I intentionally removed support for IE11 on the demo site to test speed on the evergreen browsers.
If you have problem with your app locally follow these steps: https://stackoverflow.com/q/56379067/1168786, table itself should work fine on IE11, but I focused my work on the new browsers only.

**Comment by vinayakpatil** [comment]
@ssuperczynski Works for me but in my opinion first thing anyone interested in performance would try is to look at the demo on IE11 :)

**Comment by vinayakpatil** [comment]
@ssuperczynski not sure if it's worth raising another issue but can you please share a reason for `engineStrict` on the package?
