### ISSUE TITLE
table.apiEvent sortBy not working properly?

### ISSUE THREAD

**Issue by piscisferro** [ssuperczynski/ngx-easy-table#282]
Hi!

In my project, I'm trying to make the pagination persistent between different views. For the most part, I got it working, but for some reason, the sorting is not working right, every time I set the sorting using table.apiEvent sortBy, order is always "desc", even If I hardcode it to be "asc"

Code example:

```typescript
export class TableComponent implements OnInit {

 constructor(private tablePaginationService: TablePaginationService, private cdr: ChangeDetectorRef) {
    this.configuration = { ...DefaultConfig };
    this.configuration.paginationRangeEnabled = true;
    this.configuration.paginationEnabled = true;
  }
}

  ngAfterViewInit(): void {
   this.storedPagination = this.tablePaginationService.getStoredPagination();

    if (this.storedPagination) {
      this.pagination = this.storedPagination;

      if (this.pagination.sort) {
        this.table.apiEvent({
          type: API.sortBy,
          value: { column: this.pagination.sort, order: <'asc' | 'desc'>this.pagination.order },
        });
      }

      this.cdr.detectChanges();
    }
  }
```
What I do is get the pagination and sorting from the "OnPagination" and "OnOrder" events (just like server pagination demo), then I stored it in a provider and retrieve it when needed (in this case, in the ngAfterViewInit). 

The result is that I get always a "desc" in order, I tried hardcoding asc with no results, the table just fire a "OnOrder" event with a "desc" value when setting the sortBy using the table.apiEvent. I don't know if I'm doing something wrong or the Table is not working properly :/

thanks in advance!

**Comment by Romain59000** [comment]
this.columns = [
      { key: 'name', title: 'Nom', orderBy: 'asc' },
      { key: 'code', title: 'Code' }
    ];

Same problem with sort in columns object. OrderBy is always desc...

**Comment by ssuperczynski** [comment]
Sorry, for the late answer. I don't have as much time as before to develop the new features/fix bugs. I'll try to fix this bug as as soon as possible.

**Comment by and-yiannis** [comment]
I think the problem is that the orderBy function sets the order by calling setColumnOrder (the function that is used to flip the state from asc to desc and vice versa), ignoring the order value that was stored in the local storage.
