### ISSUE TITLE
Basic example fails to run

### ISSUE THREAD

**Issue by bwbb** [ssuperczynski/ngx-easy-table#288]
I get this error when trying to setup the default example:
ASSERTION ERROR: Stored value should never be NO_CHANGE.

<img width="917" alt="Screen Shot 2020-02-19 at 9 26 20 AM" src="https://user-images.githubusercontent.com/15929544/74843772-694a4c80-52fa-11ea-8860-d7edfae409c8.png">

Maybe this is an incompatability with Angular 9?

**Comment by ssuperczynski** [comment]
Yes, work in progress. Fix will be released end of this week.

**Comment by ssuperczynski** [comment]
I've fixed this error in the 12.0.0-rc.1 release. Table now works with Angular9, but still with option `"enableIvy": false` in the tsconfig. I'm waiting for https://github.com/angular/angular/issues/35255 to be fixed.

**Comment by bwbb** [comment]
Thank you!
