### ISSUE TITLE
NO_CHANGE Error after upgrading to angular 9

### ISSUE THREAD

**Issue by yanStartapp** [ssuperczynski/ngx-easy-table#291]
Hey,

After updating to angular 9.0.4 (from 8.2.14) I'm getting an error on every page that use ngx-easy-table.

Error: ASSERTION ERROR: Stored value should never be NO_CHANGE. [Expected=> [object Object] !== [object Object] <=Actual]

Please advise.

**Comment by ssuperczynski** [comment]
This error has been resolved in version 12.0.0 Do you use this version or older?

**Comment by yanStartapp** [comment]
Works on 12.0.0.

I upgraded ngx-easy-table to 12.0.0 while running webpack dev-server, thought it will re-import, it didn't (my bad).
