### ISSUE TITLE
Column Reorder not working properly

### ISSUE THREAD

**Issue by ninjavis** [ssuperczynski/ngx-easy-table#296]
Hey there! Thank you so much for this awesome table module.

I installed it this morning and am playing around with the functionality, specifically column reordering.

On your demo page, https://ngx-easy-table.eu/#/reorder, the issue of column data being under the wrong heading exists.

Would it be possible to solve this please? I have double checked the columns: [] and data: [] values too, which seem to be fine:
```typescript
public data = [{
    phone: '+1 (934) 551-2224',
    age: 20,
    company: 'ZILLANET',
    name: 'Valentine Webb',
    isActive: false,
  }, {
    phone: '+1 (948) 460-3627',
    age: 31,
    company: 'KNOWLYSIS',
    name: 'Heidi Duncan',
    isActive: true,
  }];

this.columns = [
      { key: 'phone', title: 'Phone' },
      { key: 'age', title: 'Age' },
      { key: 'company', title: 'Company' },
      { key: 'name', title: 'Name' },
      { key: 'isActive', title: 'STATUS' },
    ];
```

![image](https://user-images.githubusercontent.com/11474529/78884610-7f9f9980-7a5b-11ea-9c5d-3bd46d8b82bd.png)

Thank you so much!

**Comment by ssuperczynski** [comment]
Sorry, for the late answer. I don't have as much time as before to develop the new features/fix bugs. I'll try to fix this bug as as soon as possible.

**Comment by septk** [comment]
any update?

**Comment by ssuperczynski** [comment]
Fixed in https://github.com/ssuperczynski/ngx-easy-table/releases/tag/13.0.2
