### ISSUE TITLE
Does NgxEasyTable support dynamic display row count setting based on available vertical space?

### ISSUE THREAD

**Issue by davoutuk** [ssuperczynski/ngx-easy-table#297]
I’m looking for an Angular data table component that will automatically change the display row count and pagination according to the available vertical display space.  

Hence, if the browser window shrinks vertically there will be fewer rows displayed in the table and more page numbers in the pagination. Conversely, if the browser window expands vertically there will be more rows in the display and a lower number of pages in the pagination.

Is this something that your component supports?   If not, can you suggest some customisations to deliver this?

**Comment by ssuperczynski** [comment]
This is possible, by minimal custom implementation from your side.
1. Go to https://ngx-easy-table.eu/#/api 
2. Open "Pagination" tab
3. See buttons "Rows 10", "Rows 3"

You can customize it by calculating your vertically screen width.
