### ISSUE TITLE
Positioning of Context Menue doesn't work properly

### ISSUE THREAD

**Issue by GretchenGit** [ssuperczynski/ngx-easy-table#298]
I integrated the context menu and found that the position of it changes in relation to the length of the table.

The example page shows the same problem. Haven't found any css solution so far.

**Comment by ssuperczynski** [comment]
Sorry, for the late answer. I don't have as much time as before to develop the new features/fix bugs. I'll try to fix this bug as as soon as possible.

**Comment by GretchenGit** [comment]
That would be cool since I still haven't found a workaround!

**Comment by ssuperczynski** [comment]
Hi @GretchenGit, How can I reproduce this bug. I just checked and context menu appears correctly.
See examples when table has 100% of the display, and 50%.
<img width="1215" alt="Screenshot 2020-06-16 at 07 13 50" src="https://user-images.githubusercontent.com/6843074/84734385-03688b80-afa1-11ea-885e-12af77fbf285.png">
![Uploading Screenshot 2020-06-16 at 07.13.40.png…]()

**Comment by GretchenGit** [comment]
Hi Sebastian, it happens when the number of rows takes more than 100% of the screen height. If you show 50 rows the context menu works fine for the first few rows but when you scroll down to see the next rows it changes.

![ngx_easytable_context](https://user-images.githubusercontent.com/58035612/84740131-2305b100-afad-11ea-925d-7c287d912822.jpg)

**Comment by ssuperczynski** [comment]
Fixed in https://github.com/ssuperczynski/ngx-easy-table/releases/tag/13.0.2
