### ISSUE TITLE
Does this library  Support for multi-rows header ?

### ISSUE THREAD

**Issue by aditbharadwaj** [ssuperczynski/ngx-easy-table#302]
![9ccd063e-e975-11e6-835b-de8903efd2cf](https://user-images.githubusercontent.com/6751554/81932805-f8b98000-9609-11ea-8408-bccb7ba2c5e0.jpg)
Does this library support this type  of multi header style ?

**Comment by ssuperczynski** [comment]
Unfortunately, table doesn't support multi header.
