### ISSUE TITLE
Infinite Scroll breaks setting style

### ISSUE THREAD

**Issue by erebrus** [ssuperczynski/ngx-easy-table#308]
As the title suggests, enabling infinite scroll (i.e. adding this.configuration.infiniteScroll = true)  cell styles breaks/disables the setting of cell styles. 
Is there a workaround for this? Is a fix for this expected? 

Tested with 12.0.0

**Comment by ssuperczynski** [comment]
Could you point me how to reproduce this. Is checked the http://localhost:4200/#/col-template by adding `this.configuration.infiniteScroll = true` and it works fine.
