### ISSUE TITLE
request a demo demostrating send different resource request with different parameters

### ISSUE THREAD

**Issue by bruceauyeung** [ssuperczynski/ngx-easy-table#31]
i have run the sample you give successfully.
it seems that ng2-easy-table requests all of data in the very one request, and then in searching and pagination,no anymore request will be sent to server. this works good if data is not big. but if we have tons of data, if still we request all of data in one request, this will lead to slow response.

i'd like to display only page #1 's data when table's pagination is enabled, when user click to jump to the next page,another request  will be sent to server to retrieve page #2 's data.

i'd like to display datas according to user's selected search criteria, for example, user like to see all persons whose name `like 'pete'`, so an underlying request like `/api/persons?name=pete` will be sent to server.

would you like to provide a demo to demostrating these two usage scenario?

many thanks to you for your great work!

**Comment by ssuperczynski** [comment]
Good question, I will add this feature to TODO list. Now we are waiting for stable angular2 release to continue development. Stay tuned, feature should be added soon
