### ISSUE TITLE
[Issue]:Not working with Angular 9

### ISSUE THREAD

**Issue by vishal1025** [ssuperczynski/ngx-easy-table#310]
On Adding ngx-easy-table in angular 9 project

package.json config

		"@angular/animations": "^9.1.11",
		"@angular/cdk": "^9.2.4",
		"@angular/common": "^9.1.11",
		"@angular/compiler": "^9.1.11",
		"@angular/core": "^9.1.11",
		"@angular/forms": "^9.1.11",

gives error

Compiling ngx-easy-table : module as esm5
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected DefaultConfigService to have an inner class declaration

giving exception of [error] Error: NGCC failed. in error logs generated.

On searching to solve this NGCC Failed issue, added
    // "angularCompilerOptions": {
    //     "enableIvy": false
    // },

which leads to other dependencies problem in the application

**Comment by ssuperczynski** [comment]
Hi @vishal1025 if you use Angular 9 then please install ngx-easy-table@12.0.0.
If you use angular 10 then ngx-easy-table@13.0.0
