### ISSUE TITLE
Merge cells depending on some conditions

### ISSUE THREAD

**Issue by jumantet** [ssuperczynski/ngx-easy-table#318]
Is it possible to merge cells for a row depending on one of its property value? 
Example: 
If `row.status === a` value - I would like to merge all the cells of the row or use a cell that spans various column.

**Comment by ssuperczynski** [comment]
You can add `colspan={{value}}` in the row template https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/template/template.component.html

**Comment by khalifa005** [comment]
I did try but didn't work for the table headers
