### ISSUE TITLE
How to show column (array of data)

### ISSUE THREAD

**Issue by chhinsras** [ssuperczynski/ngx-easy-table#319]
I have

```typescript 
export interface Call {
  id?: number;
  acceptCall: boolean;
  callReasons: CallReason[];
}

export interface CallReason {
  callId: number;
  name: string;
}
```

// This is column configuration

```typescript
 this.columns = [
  { key: 'id', title: 'Id', width: '5%'},
  { key: 'callClients.name', title: 'Clients', width: '7%'}, /// it is not showing anything
  { key: 'acceptCall', title: 'Accept Call', width: '3%' },
];
```

**Comment by ssuperczynski** [comment]
You are trying to access `callClients.name`, but the Call interface doesn't have `callClients` property. Is it a typo?

**Comment by chhinsras** [comment]
> You are trying to access `callClients.name`, but the Call interface doesn't have `callClients` property. Is it a typo?

it is not typo.

it is 'callReasons.name'




is it possible to access the array



// this is my actual response from server.
[
    {
        "id": 17,
        "acceptCall": true,
        "callClients": [
            {
                "id": 12,
                "name": "Mean thormi",
            },
            {
                "id": 10,
                "name": "Borarey",
            }
        ],
        "callReasons": [
            {
                "id": 46,
                "name": "Support Transportation"
            },
            {
                "id": 22,
                "name": "Buy Food"
            }
        ]
    },
    {
        "id": 16,
        "acceptCall": true,
        "callClients": [
            {
                "id": 12,
                "name": "Mean thormi",
            },
            {
                "id": 10,
                "name": "Borarey",
            }
        ],
        "callReasons": [
            {
                "id": 46,
                "name": "Support Transportation"
            },
            {
                "id": 22,
                "name": "Buy Food"
            }
        ]
    }
]

**Comment by chhinsras** [comment]
This is what I am thinking of // 
`{ key: 'callClients.map(c => c.nameKH)', title: 'Clients', width: '7%'}`

But not working

**Comment by ssuperczynski** [comment]
You need to build your own column template, since it is an array, not an object.

https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/col-template/col-template.component.html

**Comment by chhinsras** [comment]
I still cannot figure it out.

Could you show me how to use this template?

**Comment by chhinsras** [comment]
![Screen Shot 2020-10-06 at 3 29 56 PM](https://user-images.githubusercontent.com/31751665/95177772-cc84e280-07e8-11eb-93d5-a5ea6834ec5a.png)


I followed you and it showed object

**Comment by chhinsras** [comment]
I need to manual type the template copied from this repo to work.

<ng-template #clientTbl let-row let-rowIndex="rowIndex">
  <div *ngFor="let item of row.callClients">
    <div>{{item.name}}</div>
  </div>
</ng-template>
