### ISSUE TITLE
create dynamic table component

### ISSUE THREAD

**Issue by helmerfuentes** [ssuperczynski/ngx-easy-table#324]
**Is your feature request related to a problem? Please describe.**
necesito colocar de manera estatica el filtro global y unas configuraciones, agregue un componente que usa <ngx-table> y le mando los input()  data y input() column, al usar ng-template para dar formato a las propiedades no funciona

**TablaComponent.html**

```html
<ngx-table
  [configuration]="configuration"
  [data]="Data"
  [columns]="Columns"
  (event)="onEvent($event)"
  #table
>
</ngx-table>
```
**Sala.Component.html**
```html
<app-tabla
  [Data]="ListaSalas"
  [Columns]="Columns"
>
</app-tabla>
  <ng-template let-row let-rowIndex="rowIndex" let-column="column" #rows >
    <td>< div class="btn btn-primary">Tipo: {{ row.tipo }} </ div </ td>
</ ng-template>
```

**Sala.Component.ts**

```typescript
 @ViewChild('rows') rows: TemplateRef<any>;
 this.Columns = [
      { key : 'key', title: 'Codigo' },
      { key : 'edificio.nombre', title: 'Edificio' },
      { key : 'nombre', title : 'Sala' },
      { key : 'tipo', title: 'Tipo', cellTemplate: this.rows },
      { key : 'estado', title: 'Estado' },
      { key : 'opciones', title: 'Opciones' },
    ];
```
Template customisation does not work, nothing is reflected.

**Comment by khalifa005** [comment]
@helmerfuentes but the let-column="column" doesn't work for me how can i access it
it show column: undefined 


 <ng-template let-row let-index="index" let-column="column">
                <div [innerHTML]="customCell(row, column)" ></div>
                
                <td >
                    <h5>#</h5>
                  </td>

            </ng-template>
