### ISSUE TITLE
How to custom additionalActions method?

### ISSUE THREAD

**Issue by ainominako1996** [ssuperczynski/ngx-easy-table#327]
Hello, ngx-easy-table is the best table component!

but read all sources, i can`t find a way of custom  additionalActions

For example, i want to rewrite "Toggle Phone" to another method,

How can i rewrite it? thank you

**Comment by ssuperczynski** [comment]
Hi @ainominako1996 
this functionality is documented here https://github.com/ssuperczynski/ngx-easy-table/blob/master/src/app/demo/additional-actions-template/additional-actions-template.component.html
