### ISSUE TITLE
How to modify inside table styels from our scss file.

### ISSUE THREAD

**Issue by vijayagowri** [ssuperczynski/ngx-easy-table#335]
I am trying out Ngx-table tag inside div with some class. Trying to modify table styels but not working

**Comment by ssuperczynski** [comment]
@vijayagowri https://ngx-easy-table.eu/#/styles

**Comment by vijayagowri** [comment]
Hi,
I gone through this but table font not changing, it is not overriding.

Thanks & Regards
Vijaya gowri

**Comment by ssuperczynski** [comment]
Please check https://ngx-easy-table.eu/#content:~:text=If%20you%20would%20like%20to%20change%20table%20font
