### ISSUE TITLE
Is it possible to programmatically select a row?

### ISSUE THREAD

**Issue by davidecampello** [ssuperczynski/ngx-easy-table#339]
Hi, thank you for this library. 
Is it possible to programmatically select a row, like when selectRow is true on configuration and user click on a row?
We have this table with some marker point on a map. 
When user click on the table row highlight automatically and we can select the marker, but when the user click on the marker i can't select the row.
Thank you

**Comment by ssuperczynski** [comment]
https://ngx-easy-table.eu/#/api -> Click "Row" -> click for example "Pink"
