### ISSUE TITLE
angular 2 + webpack + ng2-easy-table

### ISSUE THREAD

**Issue by jimcho** [ssuperczynski/ngx-easy-table#35]
I like ng2-easy-table style. I based on README.md file, I have systemjs.config.js works.
In my production project, I use angular 2 + webpack + ng2-easy-table. So I won't have systemjs.config.js.
I have webpack.config.js .
But I got  error message in Firefox console:
ReferenceError: System is not defined
Would you please help check and advise ?

**Comment by ssuperczynski** [comment]
Hey, I post this answer so late, sorry for that. Project just has been upgraded to Angular4 with angular-cli support, with much better description and examples
