### ISSUE TITLE
how to set checkbox by outside component?

### ISSUE THREAD

**Issue by leffeleffe** [ssuperczynski/ngx-easy-table#354]
Can I control the outside component to check or uncheck the checkbox?

Since I have read the API doc, it mentioned `API.setCheckbox`, but I believe that API is to control whether checkbox column is displayed or not.

So I need someone help me out.

**Comment by ssuperczynski** [comment]
```typescript
this.table.apiEvent({
  type: API.toggleCheckbox,
  value: 1,
});
```
