### ISSUE TITLE
Table not updating when in dynamic loaded component

### ISSUE THREAD

**Issue by anuj509** [ssuperczynski/ngx-easy-table#387]
Hi, I have a dynamic loaded component which contains table. when I update the data, table is not updating. Kindly suggest some fix.

**Comment by anuj509** [comment]
also sometimes when we update the data variable it does not reflect in table.

**Comment by MatheusOliveira-dev** [comment]
Have you tried something like: `this.data= [... this.data]`?

**Comment by anuj509** [comment]
> Have you tried something like: `this.data = [... this.data]`?

Yes I have tried this way as well

**Comment by ssuperczynski** [comment]
@anuj509 Without an example I can't help much, but I found one issue. 
When you use ngIf:

```html
<ngx-table [configuration]="configuration" #table [data]="data" [columns]="columns" *ngIf="something"></ngx-table>
```

Please try to set static to false:

```typescript
@ViewChild('table', { static: false }) table: APIDefinition;
```

I've fixed demo page, because it was causing an error indeed.

If this is not a fix for you, please create a new bug with some code. I'll help.
