### ISSUE TITLE
Custom in-table Sort not working

### ISSUE THREAD

**Issue by gerbsen** [ssuperczynski/ngx-easy-table#391]
Hello, 
If started to use this library quite a bit. So far it's been really great and everything is possible. But now there seems to be an issue with custom sorting, which is also visible in the demo: https://ngx-easy-table.eu/#/custom-intable-sort. 

The columns **Name** and **Level** are being sorted, but the rest of the table is not sortable any more. Is there something I'm missing? 

Kind regards,
Daniel

**Comment by ssuperczynski** [comment]
I've fixed demo. Just remove `this.configuration.orderEventOnly = true;`
