### ISSUE TITLE
Header template

### ISSUE THREAD

**Issue by elementalPRESS** [ssuperczynski/ngx-easy-table#393]
Hi,
I really love your table implementation. But there is one thing I do heavily missing: to define the columns with title, with etc. in the template. This would make the usage more flexible (like in swimmlane/ngx-datatable).

Do you think this could be possible in near future?

Thx and best regards,
Lars

**Comment by ssuperczynski** [comment]
Hi @elementalPRESS. This project is feature complete, and I don't plan to add any new features.
Please create a PR, or contact me (email on Github Public page) so we can discuss the details if this is an enterprise request.
