### ISSUE TITLE
ng2-easy-table broken and does not compile

### ISSUE THREAD

**Issue by navishshanbog** [ssuperczynski/ngx-easy-table#41]
Hi,
I am new to  Angular2 and have downloaded the latest npm and node and a sample program is working. However, when I try to include your ng2-easy-table I get "(index):16 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-easy-table/app/app.component(…)" and have noticed your branch is 8 commits ahead of master.
Is there additional documentation on how to make the current master work with Angular2.

thanks in advance for your immediate response.
Navish

**Comment by ssuperczynski** [comment]
Hey, I post this answer so late, sorry for that. Project just has been upgraded to Angular4 with angular-cli support, with much better description and examples
