### ISSUE TITLE
Latest release error

### ISSUE THREAD

**Issue by BloamBla** [ssuperczynski/ngx-easy-table#411]
I'm not sure if it's bug or just me...
But could u help me understand why after the latest release my app crashes on even ng serve?

error examples:
`Error: node_modules/ngx-easy-table/lib/components/thead/thead.component.d.ts:50:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.`
`Error: node_modules/ngx-easy-table/lib/components/pagination/pagination.component.d.ts:30:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.`

dependencies version - "^15.4.1"
package-lock piece: 
`"ngx-easy-table": {`
`      "version": "15.4.1",`
`      "resolved": "https://registry.npmjs.org/ngx-easy-table/-/ngx-easy-table-15.4.1.tgz",`
`      "integrity": "sha512-04cRJHM71abU0Zewe5CN0os+A2KGnpeaVaeJNJy9Z5k6I3Ci26ZYVJJT56PefISoYAMUjvfvjJZPBMo7MSpydQ==",`
`      "requires": {`
`        "ngx-pagination": "^6.0.3",`
`        "tslib": "^2.0.0"`
`      }`
`    },`
`    "ngx-pagination": {`
`      "version": "6.0.3",`
`      "resolved": "https://registry.npmjs.org/ngx-pagination/-/ngx-pagination-6.0.3.tgz",`
`      "integrity": "sha512-lONjTQ7hFPh1SyhwDrRd5ZwM4NMGQ7bNR6vLrs6mrU0Z8Q1zCcWbf/pvyp4DOlGyd9uyZxRy2wUsSZLeIPjbAw==",`
`      "requires": {`
`        "tslib": "^2.3.0"`
`      }`
`    },`

I'm using lazy modules and import `TableModule` in each where I use table.

**Comment by ssuperczynski** [comment]
Version 15.4.0 is sponsored by the company from Fortune 500. If you need some features working with Angular 14 please contact me to talk about compensation.

**Comment by BloamBla** [comment]
No thanks. Its fixed for us(using Angular 14th). Just was unexpected and without actually what wrong because all implemented by guide.

But thank you for reply.
