### ISSUE TITLE
Is ngx-easy-table going to release new version to support for the latest Angular releases (Angular 16) ?

### ISSUE THREAD

**Issue by yeanimta** [ssuperczynski/ngx-easy-table#415]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ssuperczynski** [comment]
Fixed here https://github.com/ssuperczynski/ngx-easy-table/releases/tag/15.5.0
