### ISSUE TITLE
Can't download last 15.6.0 version from npm

### ISSUE THREAD

**Issue by apa14** [ssuperczynski/ngx-easy-table#434]
You can't download the 15.6.0 version from npm, at this time lastest version on github. Can you update it to download it and try it on Angular 17.1.0 please.

![imagen](https://github.com/ssuperczynski/ngx-easy-table/assets/56692772/97abdbbc-28f8-4e2a-8fb3-8dcad36e8769)

**Comment by ssuperczynski** [comment]
Thanks @apa14, try now.
