### ISSUE TITLE
implement infinite scroll

### ISSUE THREAD

**Issue by ssuperczynski** [ssuperczynski/ngx-easy-table#46]

**Comment by MJ10** [comment]
Hey, @ssuperczynski I would like to work on this issue, could you please provide some specific details as to how you would like this to be implemented?

**Comment by ssuperczynski** [comment]
Hey,  thank you for your interest in project. 
Could you add new parameter to `src/app/services/config-service.ts` and `src/app/model/config.ts` let's say `virtualScroll`. I haven't checked virtual scroll libs yet.

Just checked this one but it is up to you https://github.com/rintoj/angular2-virtual-scroll.
In `src/app/app.component.html` ngIf probably needs to be added in line 55, like `*ngIf="config.virtualScroll"` and the that tr replaced by virtualScroll component.

So far table doesn't have server pagination so virtual scroll should work on already loaded JSON.

Let me know if that sound ok to you

**Comment by MJ10** [comment]
@ssuperczynski Sounds good, I'll take a look at some other libraries as well. I'll try to get this done over the weekend.

**Comment by MJ10** [comment]
Hey @ssuperczynski , sorry for the delay. I tried implementing the library you mentioned, but I ran into some weird DOM related issues, and it wouldn't load the data properly. I'll still try to fix it, but just wanted to update on the progress.
