### ISSUE TITLE
Remove the BrowserModule import and replace with CommonModule

### ISSUE THREAD

**Issue by maburdi94** [ssuperczynski/ngx-easy-table#74]
https://angular.io/guide/ngmodule-faq#should-i-import-browsermodule-or-commonmodule

**Comment by ssuperczynski** [comment]
Hey @maburdi94 thanks for pointing it out.
Indeed I made mistake by placing all the components into one module. I've made PR #75, could you check if it looks ok.

**Comment by maburdi94** [comment]
@ssuperczynski When I import Table module, because table module imports BrowserModule already, my app gives me an error saying BrowserModule has already been imported. The Angular FAQ says that feature modules should not import BrowserModule. You will need to replace BrowserModule in TableModule imports with CommonModule.

**Comment by ssuperczynski** [comment]
Thanks for this info, I wasn't aware of that, since couple companies use this tables and don't get any errors :(

I've added to new files:

**index.prod.ts**
```ts
export {TableModule} from './app/table.module.prod';
```

**table.module.prod.ts** (without BrowserModule)
```ts
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { AppComponent } from './components/base/base.component';
import { AppModule } from './components/base/base.module';
import { Level, NgLoggerModule } from '@nsalaun/ng-logger';
import { CommonModule } from '@angular/common';

@NgModule({
  imports: [
    CommonModule,
    HttpClientModule,
    AppModule,
    NgLoggerModule.forRoot(Level.LOG)
  ],
  bootstrap: [AppComponent],
  exports: [AppComponent],
  providers: []
})
export class TableModule {
}
```

And I use **table.module.prod.ts** only when building `dist` package. Do you think it's ok?

**Comment by maburdi94** [comment]
@ssuperczynski I might be confused on your configuration. Why is TableModule importing AppModule, and why is the bootstrap on TableModule instead of AppModule? I might not see how this is setup. 

``typescript
@NgModule({
  declarations: [
    TableComponent,
    GlobalSearchComponent,
    CsvExportComponent,
    HeaderComponent,
    PaginationComponent,
    SearchPipe,
    PaginationPipe,
    GlobalSearchPipe,
  ],
  imports: [
    CommonModule,
    HttpClientModule
  ],
  exports: [TableComponent],
  providers: [HttpClient]
})
export class TableModule { }
```

With my limited understanding, I would expect to find something like that.

**Comment by ssuperczynski** [comment]
Thanks for that, will do changes today
