### ISSUE TITLE
Errors when more than 1 table is present on the page

### ISSUE THREAD

**Issue by rfrancisco** [ssuperczynski/ngx-easy-table#76]
Hi,

If you have 2 tables in the same page you get some weird behaviours and some errors. For example, if you perform a search (using global search or the header search inputs) and you will see that the paginator of the other table gets updated. Also if you perform a global search in the second table, for example, you get a ExpressionChangedAfterItHasBeenCheckedError error thrown by the paginator component.

At first glance it looks like the paginators of both tables are using the same service.

To test this all you have to do is add 2 tables to the same component and enable pagination and global search for both.

**Comment by ssuperczynski** [comment]
Thank you! This piece of code was written when Angular2 was in alfa. Merging to master 🚀
