### ISSUE TITLE
Pipes for a column.

### ISSUE THREAD

**Issue by kush199** [ssuperczynski/ngx-easy-table#86]
How to use the pipes for the date column in this data table?

**Comment by ssuperczynski** [comment]
Hey,
I just added date pipe to `template` example. This is one of ways to work with dates pipes.
https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Ftemplate%2Ftemplate.component.html

Another one is to add [https://momentjs.com/](https://momentjs.com/) to your project and format your object properties from component.ts
