### ISSUE TITLE
Default Rows Are Not Working !!

### ISSUE THREAD

**Issue by itsSandeepNandey** [ssuperczynski/ngx-easy-table#87]
Below is the configuration I am using :

```
import { Injectable } from '@angular/core';
import {Config} from 'ngx-easy-table/src/app/ngx-easy-table/model/config';

@Injectable()
export class ConfigService {
  public static config: Config= {
    searchEnabled: false,
    headerEnabled: true,
    orderEnabled: true,
    globalSearchEnabled: false,
    paginationEnabled: true,
    exportEnabled: true,
    clickEvent: true,
    selectRow: true,
    selectCol: false,
    selectCell: false,
    rows: 5,
    additionalActions: false,
    serverPagination: false,
    isLoading: false,
    detailsTemplate: false,
    groupRows: false
  };
}
```

But  by default , 10 Rows are loading.
**rows: 5** , configuration is not changing the default behavior .

**Comment by ssuperczynski** [comment]
Hey,
indeed, there is a problem there. I'll fix it with the new verison

**Comment by itsSandeepNandey** [comment]
Thanks Sebastian,

It will be great help if fix can be provided soon , as we are already using this data-table in one of our project in which we have to keep default row limit as 5 and we don't have much time to switch to another plugin.

**Comment by ssuperczynski** [comment]
Version `2.1.3` is now available :)

**Comment by itsSandeepNandey** [comment]
Thanks for the quick response Sebastian

Its working now :)
