### ISSUE TITLE
dinamic add row

### ISSUE THREAD

**Issue by mnovoa** [ssuperczynski/ngx-easy-table#88]
Hello, congratulations for the excellent project

a query.., how do I add a row dynamically to the table ?, I can add a row to the dataarray, but it is not reflected in the table.

Will you have an example?

thanks

**Comment by ssuperczynski** [comment]
Hey, 

component uses `changeDetection: ChangeDetectionStrategy.OnPush` so if you'd like to dynamically add rows you can do it like: 

```html
<ngx-table [configuration]="configuration"
      [data]="data"
      [columns]="columns"
      [pagination]="pagination">
</ngx-table>
```

```ts
// some operation with this.data
this.data = [...this.data]
``` 

or another example:
https://ngx-easy-table.stackblitz.io/live-update
and source code for this example
https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Flive-update%2Flive-update.component.ts

**Comment by mnovoa** [comment]
Thank you very much for the help Sebastian, but I still do not understand (I'm new in angular)

I have this code

```
import { Component, OnInit, AfterViewInit } from '@angular/core';
import { ConfigService } from './configuration.service';
import { data } from '../assets/data';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [ConfigService]
})
export class AppComponent implements OnInit,AfterViewInit {
  title = 'app';
  configuration;
  columns = [
    { key: 'status', title: 'status' },
    { key: 'amount', title: 'amount' },
    { key: 'company', title: 'Company' },
    { key: 'limit', title: 'limit' },
    { key: 'balance', title: 'balance' },
  ];

  array = [
    { 'status': 'ACTIVE', 'amount': 1, 'company': 'foo', limit: 1000, 'balance': 2000 },
    { 'status': 'INACTIVE', 'amount': 2, 'company': 'bar', limit: 1000, 'balance': 900 },
  ];

  data = []


  constructor() {
    this.configuration = ConfigService.config;

  }

  ngOnInit() {
    this.data = this.array;
  }
```

when I press a button, I call the **buton()**  function to add a new row,
but the whole table is erased.

```
boton() {
  let arr = [];
  arr.push({ 'status': 'ACTIVE', 'amount': 33, 'company': 'Some', limit: 600, 'balance': 1200 });
  this.data = [arr]
  }
```
use as base the liveupdate code as you recommended me
any help is appreciated

**Comment by ssuperczynski** [comment]
I've created demo for you.
https://stackblitz.com/edit/ngx-easy-table?file=app%2Fcomponents%2Fdynamic-row%2Fdynamic-row.component.ts

:)

**Comment by mnovoa** [comment]
Sebastian **you are a master!!**

**Comment by ssuperczynski** [comment]
You’re welcome ;)
