### ISSUE TITLE
Error : Cannot read property rows of undefined

### ISSUE THREAD

**Issue by itsSandeepNandey** [ssuperczynski/ngx-easy-table#93]
Hi,

We are getting an error with message 'cannot read property rows of undefined' .
Please help to understand the root cause of this error.

Note : This error is occurring for few users only.

**Comment by ssuperczynski** [comment]
I guess that you render table before table get response from the server.
Could you add some plunkr or stackblitz?

**Comment by itsSandeepNandey** [comment]
Thanks for the reply.

I have fixed the issue.
The problem was in initializing the configuration.

you can close the issue :)
