### ISSUE TITLE
Re-'groupRowsBy' on data change

### ISSUE THREAD

**Issue by rolandpeelen** [ssuperczynski/ngx-easy-table#95]
Hi,

When I use async data, the groupRowsBy doesn't work. I think this is because the following only runs on init:

```
Observable.from(this.data)
        .groupBy(row => row[this.groupRowsBy])
        .flatMap(group => group.reduce((acc: Array<Object>, curr) => [...acc, curr], []))
        .subscribe(row => this.grouped.push(row));
```

**Comment by rolandpeelen** [comment]
Perhaps run this in the ngOnChanges as well?

**Comment by ssuperczynski** [comment]
@rolandpeelen I've pushed version 2.3.2 with fix for this issue. Demo updated too: https://ngx-easy-table.stackblitz.io/group-rows
